### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s1-evaluacion-intermedia-elisamartinb#1]
Really good job @elisamartinb !!

Here you have some tips to finish and improve it:

- [x] Add a folder for your images
- [x] Add a proper text in your meta title
- [x] Move fonts CSS before main CSS
- [x] Improve indentation and avoid unnecessary white lines to improve readability and avoid bugs
- [x] Improve semantics, can you find candidates for an `h1` and a `ul`?
- [x] If there were justice in the world every `img` would have an `alt` attribute
- [x] Usually, logos are links to the home page
- [x] Avoid uppercase words, we can achieve this with CSS, and use HTML for semantic content
- [x] Avoid tag selectors in CSS
- [x] Try to be a little more descriptive in your commit messages, using imperative. Ex. -> Fix mobile header 

Once you have these are fixed, try to finish the exercise, start the mobile header and go step by step:

- Add/fix structural styles if needed
- Add/fix cosmetic styles if needed

Then repeat on main area, and finally do the same for the tablet version.

Extra tip: when you add a style in a tag for the mobile version, for instance `display: flex;` there is no need to repeat that instruction in media queries for bigger screens unless you want to change the style ;)

Go for it and ask me if you have any doubts ;)

**Comment by elisamartinb** [comment]
Hi @nasivuela ! Thanks for your comments!! I really appreaciate them!!

-You are absolutely right about adding a text in the meta title because I always leave the default one (not anymore!)

-As for the `ul` list, I didnt think of a list for the BLOG and CONTACT links in the first place, because I found it easier to work with `div` in a flexbox, but I changed it as you suggested and It didnt make a difference!!

-Also I dont know why the BLOG and CONTACT links still have some text decoration although I quit them (or thats what I thought ). Maybe its because I clicked on them and their color changed?

-the last thing is that I didnt understand what you meant by "avoiding tag selectors in CSS".

Thanks!! :)

**Comment by nasivuela** [comment]
Well done @elisamartinb !!

- Remember the browser apply some styles to certain tags, one of them is color on the `a` tag. Checking your code it looks like you are changing the color on the `li`.

- Example of tag selector: 

```
nav {
    width: 50%;   
}
```

It will be better to use a class ;)

***

I have also unchecked one point more related to uppercase on HTML, it will be better to have grammatically correct sentences on HTML (Ex. BLOG -> Blog) and modify them with CSS. 

***

Two last things to make it an excellent work:

- [ ] Add the link of Github Pages to the main page of your repo.
- [ ] On Tablet and desktop versions it looks like the word 'Diversidad' is slightly pushed to the right. It seems like the width of the title is to narrow and makes it move

Let's fix it!

**Comment by elisamartinb** [comment]
Done!! :smile:

**Comment by nasivuela** [comment]
You got it!

![](https://media.giphy.com/media/aQYR1p8saOQla/giphy.gif)
